config/routes.rb
Rails.application.routes.draw do
  resources :aritcles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/aritcle.rb
class Aritcle < ApplicationRecord
    validates :title ,presence: true, length: {minimum:3, maximum:100}
    validates :description ,presence: true, length: {minimum:10, maximum:100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/aritcles_controller.rb
class AritclesController < ApplicationController
  before_action :set_aritcle, only: %i[ show edit update destroy ]

  # GET /aritcles or /aritcles.json
  def index
    @aritcles = Aritcle.all
  end

  # GET /aritcles/1 or /aritcles/1.json
  def show
  end

  # GET /aritcles/new
  def new
    @aritcle = Aritcle.new
  end

  # GET /aritcles/1/edit
  def edit
  end

  # POST /aritcles or /aritcles.json
  def create
    @aritcle = Aritcle.new(aritcle_params)

    respond_to do |format|
      if @aritcle.save
        format.html { redirect_to aritcle_url(@aritcle), notice: "Aritcle was successfully created." }
        format.json { render :show, status: :created, location: @aritcle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aritcle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aritcles/1 or /aritcles/1.json
  def update
    respond_to do |format|
      if @aritcle.update(aritcle_params)
        format.html { redirect_to aritcle_url(@aritcle), notice: "Aritcle was successfully updated." }
        format.json { render :show, status: :ok, location: @aritcle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aritcle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aritcles/1 or /aritcles/1.json
  def destroy
    @aritcle.destroy

    respond_to do |format|
      format.html { redirect_to aritcles_url, notice: "Aritcle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aritcle
      begin
        @aritcle = Aritcle.find(params[:id])
      rescue => exception
        redirect_to aritcles_path, notice: exception
      end
    end

    # Only allow a list of trusted parameters through.
    def aritcle_params
      params.require(:aritcle).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aritcles_helper.rb
module AritclesHelper
end

app/views/aritcles/_aritcle.html.erb
<div id="<%= dom_id aritcle %>">
  <p>
    <strong>Title:</strong>
    <%= aritcle.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= aritcle.description %>
  </p>

</div>

app/views/aritcles/_form.html.erb
<%= form_with(model: aritcle) do |form| %>
  <% if aritcle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aritcle.errors.count, "error") %> prohibited this aritcle from being saved:</h2>

      <ul>
        <% aritcle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/aritcles/edit.html.erb
<h1>Editing aritcle</h1>

<%= render "form", aritcle: @aritcle %>

<br>

<div>
  <%= link_to "Show this aritcle", @aritcle %> |
  <%= link_to "Back to aritcles", aritcles_path %>
</div>

app/views/aritcles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Aritcles</h1>

<div id="aritcles">
  <% @aritcles.each do |aritcle| %>
    <%= render aritcle %>
    <p>
      <%= link_to "Show this aritcle", aritcle %>
    </p>
  <% end %>
</div>

<%= link_to "New aritcle", new_aritcle_path %>

app/views/aritcles/new.html.erb
<h1>New aritcle</h1>

<%= render "form", aritcle: @aritcle %>

<br>

<div>
  <%= link_to "Back to aritcles", aritcles_path %>
</div>

app/views/aritcles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aritcle %>

<div>
  <%= link_to "Edit this aritcle", edit_aritcle_path(@aritcle) %> |
  <%= link_to "Back to aritcles", aritcles_path %>

  <%= button_to "Destroy this aritcle", @aritcle, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Project01</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
	</head>

	<body>

		<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">Navbar</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Dropdown
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="#">Action</a>
					<a class="dropdown-item" href="#">Another action</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Something else here</a>
				</div>
			</li>
			<li class="nav-item">
				<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
			</li>
		</ul>
		<form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		</form>
	</div>
</nav>
		<%= yield %>
	</body>
</html>